apiVersion: v1
kind: Service
metadata:
  name: app-back-srv
  labels:
    app: backendapp-back
spec:
  type: ClusterIP
  selector:
    app: app-back
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
